engine:
    type: '99'
    max_task_process_num: 10
beanstalkc:
    queue_ip: 127.0.0.1
    queue_start_name: 'TEST_ENGINE_START'
    queue_result_name: 'TEST_ENGINE_RESULT'
mysql:
    mysql_host: 127.0.0.1
    mysql_db: test
    mysql_user: root
    mysql_password: zxy
text:
    pool_num: 10  # 线程池数量
